### ISSUE TITLE
python 3

### ISSUE THREAD

**Issue by wood-chris** [mikeagn/CEC2013#2]
I'm using the functions with python 3 - happy to submit a PR with the updated code that will be valid python 2 and 3 if this would be useful...

**Comment by mikeagn** [comment]
Hi a PR would be perfect! Looking forward to it.

**Comment by wood-chris** [comment]
Ah, I've just realised it's a bit more complicated, sorry!

My fork (https://github.com/wood-chris/CEC2013/tree/master/python) shows updates, which are both python 2 and 3 compatible; but I changed the code so that the `data` directory is in the same directory as the rest of the code. This means it's easier to just drop the `cec2013` directory in as a standalone submodule into the code I'm developing.

I'll create a new repo _just_ for the python, so it can be cloned purely as a submodule without any of the other languages. I'll let you know when I've done this, but feel free to clone/fork my code as you see fit.

**Comment by wood-chris** [comment]
Python specific repo:
https://github.com/wood-chris/cec2013-python

**Comment by wood-chris** [comment]
I've been doing a bit more work, and now added it to my departmental github: https://github.com/EPCCed/cec2013-python

**Comment by wood-chris** [comment]
Python 3 version written - it's (probably) too different to merge but feel free to fork our version :)
