### ISSUE TITLE
Python implementation: function **F7 Vincent** seems not to be working properly

### ISSUE THREAD

**Issue by juanluck** [mikeagn/CEC2013#3]
Hello,
I am getting different contours of the function **F7 Vincent** depending on whether I use the java or the python implementation:

- With the java version:

<img width="320" alt="f7VincentJava" src="https://user-images.githubusercontent.com/6534207/57971698-a8292b80-7991-11e9-8004-1a6d321d2043.png">

- With the python version:

<img width="320" alt="f7VincentPython" src="https://user-images.githubusercontent.com/6534207/57971710-c7c05400-7991-11e9-8d7c-b479a70c61c5.png">

I will try to check out more functions to see if that issue is only with F7 or not. I will also come back if I get any hint from the code. 

Thanks!

**Comment by mikeagn** [comment]
Hi juanluck, 
OK many thanks! I'll check it out and let you know
Michael.

**Comment by juanluck** [comment]
Hello Michael,

I have been testing all the functions in 2D and it seems that the issue is only with **f7 Vincent** (i.e. f = CEC2013(7))). However I don't know if the issue may also extend to  **f = CEC2013(9))** which is the 3D version of **f7 Vincent**. 
Thanks,
Juanlu

**Comment by mikeagn** [comment]
Dear Juanlu,
I assume that the problem now is fixed since we've updated the code to use the math.log method. Please reopen the ticket if the problem persists.
Many thanks.
Michael.
